workflows:
  android-release:
    name: Android Release
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      # Step 1: Set up Flutter
      - name: Set up Flutter
        script: flutter --version

      # Step 2: Get dependencies
      - name: Get dependencies
        script: flutter pub get

      # Step 3: Decode and save key.properties
      - name: Decode and save key.properties
        script: |
          echo "Decoding and saving key.properties"
          echo "$CM_KEY_PROPERTIES" | base64 --decode > android/key.properties

      # Step 4: Build APK
      - name: Build APK
        script: |
          flutter build apk --release --dart-define=FLUTTER_WEB_USE_SKIA=true

      # Step 5: Build AAB
      - name: Build AAB
        script: |
          flutter build appbundle --release --dart-define=FLUTTER_WEB_USE_SKIA=true

    artifacts:
      - "build/app/outputs/flutter-apk/app-release.apk"
      - "build/app/outputs/bundle/release/app-release.aab"
