name: Flutter CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build & Sign Android App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Print Flutter Version
        run: flutter --version

      - name: Print pubspec.yaml
        run: cat pubspec.yaml

      - name: Install dependencies
        run: flutter pub get

      - name: Run Tests
        run: flutter test

      - name: Decode Keystore
        run: echo "$KEYSTORE_BASE64" | base64 --decode > android/app/keystore.jks
        env:
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: Verify Keystore File
        run: ls -l android/app/keystore.jks

      - name: Setup Signing Properties
        run: |
          echo "storeFile=keystore.jks" > android/key.properties
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties

      - name: Verify key.properties content
        run: cat android/key.properties

      - name: Print Environment Variables
        run: |
          echo "KEYSTORE_PASSWORD is set: ${{ secrets.KEYSTORE_PASSWORD != '' }}"
          echo "KEY_ALIAS is set: ${{ secrets.KEY_ALIAS != '' }}"
          echo "KEY_PASSWORD is set: ${{ secrets.KEY_PASSWORD != '' }}"

      - name: Build Signed AppBundle
        run: flutter build appbundle --release

      - name: Upload AAB as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-appbundle
          path: build/app/outputs/bundle/release/app-release.aab
